apiVersion: v1
kind: Pod
metadata:
  name: mypod2
spec:
  containers:
  - name: nginx-priya
    image: nginx:latest
    ports:
    - containerPort: 8080 
  - name: watcher-priya
    image: afakharany/watcher     
    
